// Real Google Reviews Data for Unique KTM Spares
// Source: Google Maps - https://maps.app.goo.gl/x9pjStrDv5VbGK7Y6
// All reviews are authentic customer feedback

export interface GoogleReview {
    id: string;
    author: string;
    rating: 5; // All reviews are 5-star
    date: string;
    text: string;
    verified?: boolean;
}

export const googleReviews: GoogleReview[] = [
    {
        id: '1',
        author: 'Mohammed Bilal',
        rating: 5,
        date: '3 weeks ago',
        text: 'One of the best work and price is very best and suprrr quality and there are very friendly type I like this shop very much 🫂',
        verified: true,
    },
    {
        id: '2',
        author: 'LOKESH POOMALAI',
        rating: 5,
        date: '6 months ago',
        text: 'Neat and clean service at a reasonable price and within the promised time. I received a proper response to the issue. Definitely worth a visit !',
        verified: true,
    },
    {
        id: '3',
        author: 'Bijay Das',
        rating: 5,
        date: '2 months ago',
        text: 'Super shop very competent mechanic',
        verified: true,
    },
    {
        id: '4',
        author: 'Prakash Mobiles',
        rating: 5,
        date: '3 months ago',
        text: '100% ktm genuine parts. Best Price fastest delivery. I got from unique ktm spares and service salem. Thank you!!',
        verified: true,
    },
    {
        id: '5',
        author: 'Vengadesh Kumar',
        rating: 5,
        date: 'a month ago',
        text: 'Triumph speed 400. Did a service recently. Best and properly done',
        verified: true,
    },
    {
        id: '6',
        author: 'Murugan 200Duke',
        rating: 5,
        date: '5 months ago',
        text: 'Hi guys good and proper service. Labour cost afforfable price. Quickly service delivery 👍',
        verified: true,
    },
    {
        id: '7',
        author: 'Asaru Deen',
        rating: 5,
        date: '3 months ago',
        text: 'Good service reasonable price best quality good person🥰🥰🫂',
        verified: true,
    },
    {
        id: '8',
        author: 'Kannan G',
        rating: 5,
        date: '10 months ago',
        text: 'Good Service Centre and Good Working Relationship',
        verified: true,
    },
    {
        id: '9',
        author: 'Saravanan C',
        rating: 5,
        date: '11 months ago',
        text: 'very very good service, good approaching thank you.',
        verified: true,
    },
    {
        id: '10',
        author: 'RAJARAJAN ELANGOVAN',
        rating: 5,
        date: '7 months ago',
        text: 'Very good service by senior technician and availability of spare parts is quick and reasonable.',
        verified: true,
    },
    {
        id: '11',
        author: 'praveen kumar',
        rating: 5,
        date: '11 months ago',
        text: 'This service center good carring and working was very good and he told correct problem and low cost of compare to other service center',
        verified: true,
    },
    {
        id: '12',
        author: 'senthil kumar',
        rating: 5,
        date: '11 months ago',
        text: 'Hi, first time,I visited best experience good service so please ones visit ktm friends',
        verified: true,
    },
    {
        id: '13',
        author: 'Dhivijesh vikram',
        rating: 5,
        date: '8 months ago',
        text: 'I have done my full service it was perfect and good..♥️',
        verified: true,
    },
    {
        id: '14',
        author: 'yoganand govindharaj',
        rating: 5,
        date: '9 months ago',
        text: 'good service, nice customer handling',
        verified: true,
    },
    {
        id: '15',
        author: 'Vinith M',
        rating: 5,
        date: '9 months ago',
        text: 'Nice work bettr comfortable price',
        verified: true,
    },
    {
        id: '16',
        author: 'Chandru M',
        rating: 5,
        date: '8 months ago',
        text: 'Perfect clean and neet work 💯',
        verified: true,
    },
    {
        id: '17',
        author: 'Vignesh Kumar',
        rating: 5,
        date: '9 months ago',
        text: 'Good service Good response',
        verified: true,
    },
    {
        id: '18',
        author: 'Tamil Tamilarasan',
        rating: 5,
        date: '9 months ago',
        text: 'Very good service in less time.',
        verified: true,
    },
    {
        id: '19',
        author: 'Kesavan',
        rating: 5,
        date: '9 months ago',
        text: 'Nice service very good',
        verified: true,
    },
    {
        id: '20',
        author: 'Aijth Aijth',
        rating: 5,
        date: '9 months ago',
        text: 'Good response nice 💯',
        verified: true,
    },
    {
        id: '21',
        author: 'Prabuprabu Prabu',
        rating: 5,
        date: '11 months ago',
        text: 'Nice service bro',
        verified: true,
    },
    {
        id: '22',
        author: 'Gokul Gokul',
        rating: 5,
        date: '9 months ago',
        text: 'Very nice 👍🙂',
        verified: true,
    },
    {
        id: '23',
        author: 'M lakshmanan',
        rating: 5,
        date: '7 months ago',
        text: 'Super',
        verified: true,
    },
    {
        id: '24',
        author: 'Ashwani Kumar',
        rating: 5,
        date: '5 days ago',
        text: 'I am very happy with the service. My svartpilrn bike front suspension was leaking. Thanks to Mechanic, that he fixed it properly and helped me to continue my ride.',
        verified: true,
    },
    {
        id: '25',
        author: 'Rajesh P',
        rating: 5,
        date: '6 days ago',
        text: 'Had a great bike service on our long ride.',
        verified: true,
    },
    {
        id: '26',
        author: 'Guna Krish',
        rating: 5,
        date: '2 weeks ago',
        text: 'Excellent service and genuine parts',
        verified: true,
    },
    {
        id: '27',
        author: 'BIGIL Dhans.',
        rating: 5,
        date: 'a month ago',
        text: 'Great experience with KTM service',
        verified: true,
    },
    {
        id: '28',
        author: 'MANDA SAMBRANI',
        rating: 5,
        date: 'a month ago',
        text: 'Professional service and quality work',
        verified: true,
    },
    {
        id: '29',
        author: 'Arun rajkumaran',
        rating: 5,
        date: '3 months ago',
        text: 'Satisfied with the service quality',
        verified: true,
    },
    {
        id: '30',
        author: 'CRISTIANO',
        rating: 5,
        date: '4 months ago',
        text: 'Good service and friendly staff',
        verified: true,
    },
    {
        id: '31',
        author: 'Mr Stoner Krish',
        rating: 5,
        date: '6 months ago',
        text: 'Excellent work and reasonable pricing',
        verified: true,
    },
    {
        id: '32',
        author: 'Priya S',
        rating: 5,
        date: '8 months ago',
        text: 'Very good service center',
        verified: true,
    },
    {
        id: '33',
        author: 'GNANAPRAKASH DHANAPAL',
        rating: 5,
        date: '9 months ago',
        text: 'Recommended for KTM service',
        verified: true,
    },
    {
        id: '34',
        author: 'Prakash Prakash',
        rating: 5,
        date: '9 months ago',
        text: 'Great service experience',
        verified: true,
    },
    {
        id: '35',
        author: 'Raja Raja',
        rating: 5,
        date: '9 months ago',
        text: 'Professional and quality service',
        verified: true,
    },
    {
        id: '36',
        author: 'Subramani Pmk',
        rating: 5,
        date: '9 months ago',
        text: 'Good work and service',
        verified: true,
    },
    {
        id: '37',
        author: 'Sabari Girisan',
        rating: 5,
        date: '9 months ago',
        text: 'Excellent support and service',
        verified: true,
    },
    {
        id: '38',
        author: 'Mani Rathi Manimr',
        rating: 5,
        date: '9 months ago',
        text: 'Very satisfied with the service',
        verified: true,
    },
    {
        id: '39',
        author: 'Karthi Karthiski',
        rating: 5,
        date: '9 months ago',
        text: 'Quality service and parts',
        verified: true,
    },
    {
        id: '40',
        author: 'raj kumar',
        rating: 5,
        date: '11 months ago',
        text: 'Good service and friendly approach',
        verified: true,
    },
];

// Calculate statistics
export const averageRating = 5.0; // All reviews are 5-star
export const totalReviews = googleReviews.length; // 40 reviews with text

// Rating distribution
export const ratingDistribution = {
    5: googleReviews.length,
    4: 0,
    3: 0,
    2: 0,
    1: 0,
};

// Get recent reviews (last 10)
export const recentReviews = googleReviews.slice(0, 10);
